server:
  port: 8088

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://localhost:3306/shopapp?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true # Set to true if you want to see SQL statements in the console
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

api:
  prefix: api/v1